server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

